---

- name: End tasks on host
  meta: end_host
  when:
    - not ansible_enable|bool

- name: Include tasks for RHEL 7
  include_tasks: apache-redhat7.yml
  when:
    - apache_role_enable|bool
    - ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

- name: Include tasks for RHEL 6
  include_tasks: apache-redhat6.yml
  when:
    - apache_role_enable|bool
    - ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "6"